server:
  port: 8080

mqtt:
  client-id-prefix: dev
  server-uris: tcp://broker.emqx.io:1883
  username: admin
  password: abc@123
  keep-alive-interval: 60
  message-mapper: org.sample.mqtt.component.support.MqttJsonMessageMapper #使用JSON序列化
  #message-mapper: org.sample.mqtt.component.support.MqttProtostuffMessageMapper #使用Protostuff序列化
  model-packages: org.sample.mqtt.model.toserver #传输模型所在的包
  sub-topics:
    - $SYS/brokers/+/clients/#   #EMQX支持订阅上下线通知
    - iot_server/#               #服务端订阅
    - iot_client/test123/#       #模拟终端回复设备ID为test123