server:
  port: 8080

mqtt:
  client-id-prefix: dev
  server-uris: tcp://127.0.0.1:1883
  username: admin
  password: abc@123
  keep-alive-interval: 60
  #模拟终端回复订阅iot_client/ 设备ID为test123
  sub-topics: iot_server/#,$SYS/brokers/+/clients/#,iot_client/test123/#
  message-mapper: org.sample.mqtt.component.support.MqttJsonMessageMapper
#  message-mapper: org.sample.mqtt.component.support.MqttProtostuffMessageMapper
  model-packages: org.sample.mqtt.model.toserver,org.sample.mqtt.model.toclient