server:
  port: 8080

mqtt:
  client-id-prefix: dev
  server-uris: tcp://127.0.0.1:1883
  username: admin
  password: abc@123
  keep-alive-interval: 60
  sub-topics: mqtt/#,$SYS/brokers/+/clients/#
  converter-class: org.sample.mqtt.support.BytesMessageConverter
#  converter-class: org.springframework.integration.mqtt.support.DefaultPahoMessageConverter